### ISSUE TITLE
No results returned for custom perspectives with .v or .lv

### ISSUE THREAD

**Issue by autonomygaps** [rhydlewis/search-omnifocus#38]
I've been having this issue for a while: no results returned for custom perspectives with .v or .lv.  The only result returned are for default perspectives.  Just did a fresh re-install of the workflow, and ran the "use-of-3" because I am on OmniFocus 3.2.1 (v122.6 r325053).  I can't see what the problem is.

**Comment by rhydlewis** [comment]
Can you:

1. open Script Editor.app
2. press ⌘-N to create a new script
3. paste the attached AppleScript into the window
4. press ⌘-R to run the script
5. paste the text from the Result pane in a comment to this issue

please?

Cheers,
Rhyd

[list_perspectives.txt](https://github.com/rhydlewis/search-omnifocus/files/2909159/list_perspectives.txt)

**Comment by autonomygaps** [comment]
Hi Rhyd,

Here you go.

Looks like I have some housekeeping to do!

I believe that the “missing value” items are the default perspectives.

If the problem’s on my end, it would be great if you could let me know what I need to do!

Joel




{missing value, "Flagged Inbox", "Dashboard", "Dashboard+", missing value, "Projects All", missing value, "Now - Today - Current (Tags)", missing value, missing value, missing value, "Engaged - Parked", "Completed", "Changed", "A.M. Review", "Priority Projects", "Add 1w", "Admissions RMA", "TCHa & SPV", "Added", "All unFlagged Due", "Break Activities", "Completed navigation to purge", "Considering", "Current by Flag", "DPTa", "DPTf", "Dashboard-all", "Dormant", "Due & Available", "Due-Avl-All", "Due-Rem-All", "EmailFlagged", "FLAGa", "FLAGf - non-project mode", "Fiddle", "Flag-Rem by Project", "Flagged Projects", "Flagged by Project", "Navigation Flagged", "No Contexts", "Now By Flag", "Now By Project", "Now!", "Old \"Engage\" To Delete", "OmniFocus", "On Hold", "P.M. Review", "Hot Inbox", "PERa", "PERf", "–––––––––––––––––––––", "PER (Thurs)", "PRF (Mon)", "RES (Tues)", "TCH&SPV (Wed)", "RMA&DPT (Sun)", "SYS (Fri)", "PRFa", "PRFf", "RESf", "BOOK", "RESa", "RMA!", "RMAa", "RMAf", "Read", "SYSa", "SYSf", "–––––––––––––––––––––", "Admin - Forms - Declaraties", "Looking Forward", "Search", "Someday Maybe", "Stalled", "Start-All", "Start-Hot", "Starting", "TCHf", "Task Lists", "Templates", "Today", "Next", "Paused or Waiting For", "Weekly Review (Saturdays)", "Workspace", "Workspace - available", "–––––––––––––––––––––", "–––––––––––––––––––––", "Priority Projects", "Perspective with search terms", "Test On  IOS", "Respond to email", "Soon (CGP Gray)", "", "Widget (CGP Gray)", "E", "Copy of –––––––––––––––––––––", ""}

**Comment by rhydlewis** [comment]
Can you try this? Rename any perspectives containing the "–" character e.g. "–––––––––––––––––––––" or "Copy of –––––––––––––––––––––" so that they don't contain that character. This should solve the problem.

**Comment by autonomygaps** [comment]
Did that, but it’s still not working, even after a restart.  Here’s the current output.

I also went through and made sure all the perspectives are updated to OF3 (they were still a bit mixed).

And I did a system restart.

Could it be the “+”? Or the “&”.  Before I start removing all punctuation, I thought I’d check.

Best,

Joel

{missing value, "Flagged Inbox", "Dashboard", "Dashboard+", missing value, "Projects All", missing value, "Now - Today - Current (Tags)", missing value, missing value, missing value, "Engaged - Parked", "Completed", "Changed", "AM Review", "Priority Projects", "Add 1w", "Admissions RMA", "TCHa & SPV", "Added", "All unFlagged Due", "Break Activities", "Completed navigation to purge", "Considering", "DPTa", "DPTf", "Dashboard-all", "Dormant", "EmailFlagged", "Fiddle", "Flagged by Project", "Now By Flag", "Now By Project", "Now!", "Old Engage To Delete", "PM Review", "Hot Inbox", "PERa", "PERf", "PER (Thurs)", "PRF (Mon)", "RES (Tues)", "TCH&SPV (Wed)", "RMA&DPT (Sun)", "SYS (Fri)", "PRFa", "PRFf", "RESf", "BOOK", "RESa", "RMA!", "RMAa", "RMAf", "Read", "SYSa", "SYSf", "ZZZZZ", "Admin - Forms - Declaraties", "Looking Forward", "Search", "Someday Maybe", "Stalled", "Start-All", "Start-Hot", "Starting", "TCHf", "Task Lists", "Templates", "Today", "Next", "Paused or Waiting For", "Weekly Review (Saturdays)", "Workspace", "Priority Projects", "Respond to email", "Soon (CGP Gray)", "Widget (CGP Gray)"}

**Comment by rhydlewis** [comment]
Punctuation shouldn't be a problem (I added a perspective called "TCHa & SPV" and it works for me). Plan B: can you open Alfred's Preferences and send me the debug log?

* Show Alfred preferences (keyword 'alf')
* Click 'Workflows' in the tool bar
* Choose 'Search Omnifocus' from the list of workflows on the left
* Click on the 'Debug' to toggle debugging mode (see [Alfred's help page for more info](https://www.alfredapp.com/help/workflows/advanced/debugger/))
* Choose 'All information' from the Log dropdown
* Open Alfred and type `.lv`
* Copy the debug output and post it as a response

Cheers

**Comment by autonomygaps** [comment]
Dear Rhyd,

I really appreciate you working with me on this!  Here’s the debugger output, as well as a screenshot from the behavior I see.

Joel

[2019-03-01 07:07:45][input.scriptfilter] Queuing argument ''
[2019-03-01 07:07:45][input.scriptfilter] Script with argument '(null)' finished
[2019-03-01 07:07:45][STDERR: input.scriptfilter] .
07:07:45 workflow.py:2055 DEBUG    ---------- Search OmniFocus (2.0.4) ----------
07:07:45 workflow.py:1462 DEBUG    reading settings from /Users/joel/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/settings.json
07:07:45 workflow.py:2339 DEBUG    update check not due
07:07:45 search.py:48 DEBUG    Started workflow
07:07:45 search.py:179 DEBUG    [u'-t', u'v']
07:07:45 workflow.py:1689 DEBUG    loading cached data: /Users/joel/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/__workflow_update_status.cpickle
07:07:45 workflow.py:2269 DEBUG    update_data: {u'available': False}
07:07:45 search.py:57 INFO     Using OmniFocus version 3
07:07:45 search.py:193 DEBUG    Using stored icon_root:'/Applications/OmniFocus.app/Contents/Resources'
07:07:45 search.py:110 DEBUG    Finding all perspectives
07:07:45 search.py:117 DEBUG    Inbox
07:07:45 search.py:119 DEBUG    Perspective: Inbox, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
07:07:45 search.py:117 DEBUG    Projects
07:07:45 search.py:119 DEBUG    Perspective: Projects, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
07:07:45 search.py:117 DEBUG    Tags
07:07:45 search.py:119 DEBUG    Perspective: Tags, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
07:07:45 search.py:117 DEBUG    Forecast
07:07:45 search.py:119 DEBUG    Perspective: Forecast, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
07:07:45 search.py:117 DEBUG    Flagged
07:07:45 search.py:119 DEBUG    Perspective: Flagged, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
07:07:45 search.py:117 DEBUG    Review
07:07:45 search.py:119 DEBUG    Perspective: Review, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
07:07:45 search.py:117 DEBUG    
07:07:45 search.py:119 DEBUG    Perspective: , (), Omnifocus Custom Perspective, /Applications/OmniFocus.app/Contents/Resources/Perspectives@2x.png
07:07:45 workflow.py:2248 DEBUG    set last run version: 2.0.4
07:07:45 workflow.py:2097 DEBUG    ---------- finished in 0.226s ----------
[2019-03-01 07:07:45][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>Inbox</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Inbox</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Projects</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Projects</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Tags</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Tags</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Forecast</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Forecast</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Flagged</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Flagged</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Review</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Review</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title /><subtitle>Omnifocus Custom Perspective</subtitle><icon>/Applications/OmniFocus.app/Contents/Resources/Perspectives@2x.png</icon></item></items>

**Comment by rhydlewis** [comment]
This is the perplexing bit:

```07:07:45 search.py:117 DEBUG
07:07:45 search.py:119 DEBUG    Perspective: , (), Omnifocus Custom Perspective, /Applications/OmniFocus.app/Contents/Resources/Perspectives@2x.png```

I'll send you a debug version of the workflow to see why this is happening.

**Comment by rhydlewis** [comment]
Hi Joel,

Can you download, unzip and then import the attached workflow please? Once done, can you re-run `.lv` with the Alfred log open and share the results with me please?

[Search OmniFocus v2.0.4.debug.alfredworkflow.zip](https://github.com/rhydlewis/search-omnifocus/files/2927538/Search.OmniFocus.v2.0.4.debug.alfredworkflow.zip)

Cheers,
Rhyd

**Comment by autonomygaps** [comment]
I was only able to get to it now. 
Here is the output.

Hope this gives you some insight.

Joel


Starting debug for 'Search OmniFocus'

[2019-03-04 23:05:19][input.scriptfilter] Queuing argument ''
[2019-03-04 23:05:20][input.scriptfilter] Script with argument '(null)' finished
[2019-03-04 23:05:20][STDERR: input.scriptfilter] .
23:05:20 workflow.py:2055 DEBUG    ---------- Search OmniFocus (2.0.4) ----------
23:05:20 workflow.py:1462 DEBUG    reading settings from /Users/joel/Library/Application Support/Alfred 3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/settings.json
23:05:20 workflow.py:2334 INFO     checking for update ...
23:05:20 background.py:233 DEBUG    [__workflow_update_check] command cached: /Users/joel/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/__workflow_update_check.argcache
23:05:20 background.py:237 DEBUG    [__workflow_update_check] passing job to background runner: [u'/usr/bin/python', '/Users/joel/Dropbox/SyncLibrary/AlfredSyncViaDropbox/Alfred.alfredpreferences/workflows/user.workflow.EC49F763-0A06-4B18-868E-9FF0749B5AA8/workflow/background.pyc', u'__workflow_update_check']
.
23:05:20 workflow.py:2055 DEBUG    ---------- Search OmniFocus (2.0.4) ----------
23:05:20 background.py:243 DEBUG    [__workflow_update_check] background job started
23:05:20 search.py:48 DEBUG    Started workflow
23:05:20 search.py:179 DEBUG    [u'-t', u'v']
23:05:20 workflow.py:1689 DEBUG    loading cached data: /Users/joel/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.rhydlewis.alfred.searchomnifocus/__workflow_update_status.cpickle
23:05:20 workflow.py:2269 DEBUG    update_data: {u'available': False}
23:05:20 search.py:57 INFO     Using OmniFocus version 3
23:05:20 search.py:193 DEBUG    Using stored icon_root:'/Applications/OmniFocus.app/Contents/Resources'
23:05:20 search.py:110 DEBUG    Finding all perspectives
23:05:20 omnifocus.py:28 DEBUG    >>> ['']
23:05:20 search.py:117 DEBUG    Inbox
23:05:20 search.py:119 DEBUG    Perspective: Inbox, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
23:05:20 search.py:117 DEBUG    Projects
23:05:20 search.py:119 DEBUG    Perspective: Projects, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
23:05:20 search.py:117 DEBUG    Tags
23:05:20 search.py:119 DEBUG    Perspective: Tags, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
23:05:20 search.py:117 DEBUG    Forecast
23:05:20 search.py:119 DEBUG    Perspective: Forecast, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
23:05:20 search.py:117 DEBUG    Flagged
23:05:20 search.py:119 DEBUG    Perspective: Flagged, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
23:05:20 search.py:117 DEBUG    Review
23:05:20 search.py:119 DEBUG    Perspective: Review, (), Omnifocus Default Perspective, /Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png
23:05:20 search.py:117 DEBUG    
23:05:20 search.py:119 DEBUG    Perspective: , (), Omnifocus Custom Perspective, /Applications/OmniFocus.app/Contents/Resources/Perspectives@2x.png
23:05:20 workflow.py:2248 DEBUG    set last run version: 2.0.4
23:05:20 workflow.py:2097 DEBUG    ---------- finished in 0.360s ----------
[2019-03-04 23:05:20][input.scriptfilter] <?xml version="1.0" encoding="utf-8"?>
<items><item valid="yes"><title>Inbox</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Inbox</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Projects</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Projects</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Tags</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Tags</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Forecast</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Forecast</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Flagged</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Flagged</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title>Review</title><subtitle>Omnifocus Default Perspective</subtitle><arg>Review</arg><icon>/Applications/OmniFocus.app/Contents/Resources/AppIcon-Credits.png</icon></item><item valid="yes"><title /><subtitle>Omnifocus Custom Perspective</subtitle><icon>/Applications/OmniFocus.app/Contents/Resources/Perspectives@2x.png</icon></item></items>

**Comment by rhydlewis** [comment]
Aargh! This line shows no perspectives returned from the AppleScript call:

`23:05:20 omnifocus.py:28 DEBUG    >>> ['']`

Back to the drawing board. I'll have another think...

**Comment by rhydlewis** [comment]
Hi Joel,

If you install and run this workflow:

[List Omnifocus Perspectives.alfredworkflow.zip](https://github.com/rhydlewis/search-omnifocus/files/2971810/List.Omnifocus.Perspectives.alfredworkflow.zip) 

(which should get your list of perspectives and display them as a comma separated list), do you see output like this:

<img width="400" alt="example output" src="https://user-images.githubusercontent.com/2102276/54443443-88c71580-4738-11e9-910f-ba3b4951622b.png">

Reason I'm asking: I'm trying to work out if there's a permission issue that prevents the workflow from getting access to your perspectives.

Cheers,
Rhyd

**Comment by autonomygaps** [comment]
Doesn’t seem to be working.  No text popped up.  Here’s the bug report.
I sure hope this isn’t something quirky on my machine that is throughing things off.
I’ve tried this new workflow on my laptop (also running Mojave), and it first requested permissions for Alfred to access OmniFocus 3, and then it delivered the popup with the comma-separated text. Still, the laptop has the same problem of giving me an error message when I search for perspectives, with .v.  
But popup just doesn't happen on my main machine, a 5K iMac. 
Joel


Starting debug for 'List Omnifocus Perspectives'

[2019-03-15 23:21:36][input.keyword] Processing output of 'action.applescript' with arg ''
[2019-03-15 23:21:36][action.applescript] Processing output of 'output.largetype' with arg ''

**Comment by rhydlewis** [comment]
I'm stumped - sorry. It feels like a permission issue (i.e. the workflow isn't allowed to run the AppleScript to get the names of the perspectives) or the workflow doesn't cope well with unicode text in the perspective text. Since you're seeing different results on your iMac compared to your laptop is also muddying the water a little.

I'll have another think but not sure I'll be able to resolve this anytime soon.

**Comment by autonomygaps** [comment]
I really appreciate your efforts.  I have workarounds, and if I’m the only one you hear from, then let’s just hope it all disappears at some point.

Joel
